config/routes.rb
FreddieFit::Application.routes.draw do
  resources :foods

  get "home/index"

  resources :announcements

  resources :events

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  match 'event/register' => 'events#register', :as => :register_for_event  
  match 'event/unregister' => 'events#unregister', :as => :unregister_for_event

  match 'show_classes' => 'events#show_classes', :as => :show_classes

  match 'food/favorites/add' => 'foods#add_favorite', :as => :add_favorite_food
  match 'food/favorites/remove' => 'foods#remove_favorite', :as => :remove_favorite_food
  match 'food/mark_as_eaten' => 'foods#mark_as_eaten', :as => :mark_food_as_eaten
  match 'food/unmark_as_eaten' => 'foods#unmark_as_eaten', :as => :unmark_food_as_eaten

  resources :sessions

  resources :users

  root :to => 'home#index'

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  attr_accessible :title, :date, :description, :classification

  ANNOUNCEMENT_TYPES = [['Fitness', 0], ['Food', 1]]

end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  def index
    @announcements = Announcement.all
  end

  def show
    @announcement = Announcement.find(params[:id])
  end

  def new
    @announcement = Announcement.new
  end

  def create
    @announcement = Announcement.new(params[:announcement])
    if @announcement.save
      redirect_to @announcement, :notice => "Successfully created announcement."
    else
      render :action => 'new'
    end
  end

  def edit
    @announcement = Announcement.find(params[:id])
  end

  def update
    @announcement = Announcement.find(params[:id])
    if @announcement.update_attributes(params[:announcement])
      redirect_to @announcement, :notice  => "Successfully updated announcement."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @announcement = Announcement.find(params[:id])
    @announcement.destroy
    redirect_to announcements_url, :notice => "Successfully destroyed announcement."
  end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
	def show_date(start_date)

		if start_date.nil?
			return "TBD"
		else 
			return start_date.strftime("%B %d, %Y" )
		end

	end

end

app/views/announcements/_form.html.erb
<script>
  $(function() {
    $( "#announcement_date" ).datepicker({ dateFormat: 'dd-mm-yy' });
  });
</script>

<%= form_for @announcement do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :date %><br />
    <%= f.text_field :date %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :classification %><br />
    <%= f.select :classification, Announcement::ANNOUNCEMENT_TYPES, :prompt => "Select an announcement type." %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/announcements/edit.html.erb
<% title "Edit Announcement" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @announcement %> |
  <%= link_to "View All", announcements_path %>
</p>

app/views/announcements/index.html.erb
<div id="nav-header">
  <br />
  <h2>News & Announcements</h2> 
  <% if can? :create, Announcement %>
    <h3 class="title"><%= link_to(image_tag('icons/add.gif', :size => '20x20'), new_announcement_path) %></h3>
  <% end %>
</div>
<br />
<div id="page-content">
<% if !@announcements.empty? %> 
<table class="datagrid" style="text-align: center; margin-left: auto; margin-right: auto">
  <thead class="datagrid">
    <% if can? :modify, Announcement %>
      <th></th>
    <% end %>
    <th>Title</th>
    <th>Date</th>
    <% if can? :modify, @announcement %>
      <th>Active</th>
      <th></th>
    <% end %>
  </thead>

  <% @announcements.each do |announcement| %>
  <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
    <% if can? :modify, announcement %>
      <td><%= link_to(image_tag('icons/edit.png', :border => 0, :size => "20x20"), edit_announcement_path(announcement)) %></td>
    <% end %>
    <td><%= link_to(announcement.title, announcement) %></td>
    <td><%= show_date(announcement.date) %></td>
    <% if can? :modify, announcement %>
      <td><%= link_to(image_tag('icons/trash.gif', :border => 0, :size => "20x20"), announcement, :confirm => 'Are you sure?', :method => :delete)  %></td>
    <% end %>
  </tr
  <% end %>
</table>

<% else %>

  <p><em>There are no announcements.</em></p>
  
<% end %>
</div>

app/views/announcements/new.html.erb
<% title "New Announcement" %>

<%= render 'form' %>

<p><%= link_to "Back to List", announcements_path %></p>

app/views/announcements/show.html.erb
<% title "Announcement" %>

<p>
  <strong>Title:</strong>
  <%= @announcement.title %>
</p>
<p>
  <strong>Date:</strong>
  <%= @announcement.date %>
</p>
<p>
  <strong>Description:</strong>
  <%= @announcement.description %>
</p>
<p>
  <strong>Classification:</strong>
  <%= @announcement.classification %>
</p>

<p>
  <%= link_to "Edit", edit_announcement_path(@announcement) %> |
  <%= link_to "Destroy", @announcement, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", announcements_path %>
</p>