config/routes.rb
FreddieFit::Application.routes.draw do
  resources :foods

  get "home/index"

  resources :announcements

  resources :events

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  match 'event/register' => 'events#register', :as => :register_for_event  
  match 'event/unregister' => 'events#unregister', :as => :unregister_for_event

  match 'show_classes' => 'events#show_classes', :as => :show_classes

  match 'food/favorites/add' => 'foods#add_favorite', :as => :add_favorite_food
  match 'food/favorites/remove' => 'foods#remove_favorite', :as => :remove_favorite_food
  match 'food/mark_as_eaten' => 'foods#mark_as_eaten', :as => :mark_food_as_eaten
  match 'food/unmark_as_eaten' => 'foods#unmark_as_eaten', :as => :unmark_food_as_eaten

  resources :sessions

  resources :users

  root :to => 'home#index'

end

app/models/food.rb
class Food < ActiveRecord::Base
  attr_accessible :name, :description, :food_type, :calories, :cost

  has_many :food_locations
  has_many :favorite_foods

  FOOD_TYPES = [['None', 0], ['FIT', 1], ['VEGAN', 2], ['FIT VEGAN', 3]]
  LOCATIONS = [['PHO I', 0], ['PHO II', 1], ['PHO III', 2], ['PHO IV', 3], ['8K', 4]]

  def show_food_type
  	unless self.food_type.nil? then 
      return FOOD_TYPES[self.food_type][0]
    end
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.all
  end

  def show
    @food = Food.find(params[:id])
    session[:food_id] = @food.id
    @favorite = FavoriteFood.where(:user_id => session[:user_id], :food_id => @food.id).first
    @ef = UserFood.where(:user_id => session[:user_id], :food_id => @food.id).first
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(params[:food])
    if @food.save
      redirect_to @food, :notice => "Successfully created food."
    else
      render :action => 'new'
    end
  end

  def edit
    @food = Food.find(params[:id])
  end

  def update
    @food = Food.find(params[:id])
    if @food.update_attributes(params[:food])
      redirect_to @food, :notice  => "Successfully updated food."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to foods_url, :notice => "Successfully destroyed food."
  end


  def add_favorite
    @ff = FavoriteFood.new
    @ff.food_id = params[:food_id]
    @ff.user_id = session[:user_id]

    if @ff.save
      redirect_to :back, :notice => "Food marked as favorite."
    else
      redirect_to :back, :alert => "Could not add food as favorite."
    end

  end

  def remove_favorite
    @favorite = FavoriteFood.find(params[:favorite_id])

    if @favorite.destroy
      redirect_to Food.find(session[:food_id]), :notice => "You removed this food as a favorite."
    else
      redirect_to Food.find(session[:food_id]), :alert => "Unable to remove food from favorites."
    end

  end

  def mark_as_eaten
    @ef = UserFood.new
    @ef.food_id = params[:food_id]
    @ef.user_id = session[:user_id]

    if @ef.save
      redirect_to :back, :notice => "Marked food as eaten."
    else
      redirect_to :back, :alert => "Could not mark food as eaten."
    end

  end

  def unmark_as_eaten

    puts params[:ef_id]

    @ef = UserFood.find(params[:ef_id])


    if @ef.destroy
      redirect_to Food.find(session[:food_id]), :notice => "You removed this food as a favorite."
    else
      redirect_to Food.find(session[:food_id]), :alert => "Unable to remove food from favorites."
    end
  end

  def new_menu
    @fl = FoodLocation.new
  end

  def create_menu
    @fl = FoodLocation.new(params[:food_location])
    if @fl.save
      redirect_to @fl, :notice => "Successfully created food."
    else
      render :action => 'new_menu'
    end

  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.html.erb
<%= form_for @food do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :food_type %><br />
    <%= f.select :food_type, Food::FOOD_TYPES, :prompt => "What type?" %>
  </p>
  <p>
    <%= f.label :calories %><br />
    <%= f.number_field :calories %>
  </p>
  <p>
    <%= f.label :cost %><br />
    <%= f.text_field :cost %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/foods/edit.html.erb
<% title "Edit Food" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @food %> |
  <%= link_to "View All", foods_path %>
</p>

app/views/foods/index.html.erb
<div id="nav-header">
  <br />
  <h2>Foods</h2> 
  <% if can? :create, Food%>
    <h3 class="title"><%= link_to(image_tag('icons/add.gif', :size => '20x20'), new_food_path) %></h3>
  <% end %>
</div>
<div id="foods">

  <% if !@foods.empty? %>
  <table class   = "datagrid">
    <thead class = "datagrid">
      <% if can? :modify, Food %>
      <th></th>
      <% end %>
      <th>Name</th>
      <th>Type</th>
      <th>Calories</th>
      <th>Cost</th>
      <% if can? :modify, Food %>
      <th></th>
      <% end %>
    </thead>

    <% @foods.each do |food| %>
    <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
      <% if can? :modify, food %>
      <td><%= link_to image_tag('icons/edit.png', :border => 0, :size => "20x20"), edit_food_path(food) %></td>
      <% end %>
      <td><%= link_to food.name, food %></td>
      <td><%= food.show_food_type %></td>
      <td><%= food.calories %></td>
      <td><%= number_to_currency(food.cost) %></td>
      <% if can? :modify, Food %>
      <td><%= link_to image_tag('icons/trash.gif', :border => 0, :size => "20x20"), food, :confirm => 'Are you sure?', :method => :delete  %></td> 
      <% end %>
    </tr>
    <% end %>
  </table>
  <% else %>

  <p>
    There are no created foods. 
    <% if can? :create, Food %>
    Create one <%= link_to "here", new_food_path %>.
    <% end %>
  </p>

  <% end %>
</div>

app/views/foods/new.html.erb
<% title "New Food" %>

<%= render 'form' %>

<p><%= link_to "Back to List", foods_path %></p>

app/views/foods/new_menu.html.erb
<% title 'Create a menu item' %>

  <div class="field">
    <%= f.label :food %>:  <%= f.collection_select :food_id, Food.all, :id, :name, :prompt => "Please select a food." %>
  </div>

  <div class="field">
      <%= f.label :location %>:  <%= f.select :location_id, Food::LOCATIONS, :prompt => "Where at?" %>
   </div>

app/views/foods/show.html.erb
<% if !@favorite.nil? && can?(:modify, @favorite) %>
<%= link_to image_tag('icons/unstar.gif', :border => 0, :size => "20x20"), { :controller => 'foods', :action => 'remove_favorite', :favorite_id => @favorite.id }, :class => :destroy %>
<% elsif logged_in? %>
<%= link_to image_tag('icons/star.gif', :border => 0, :size => "20x20"), { :controller => 'foods', :action => 'add_favorite', :food_id => @food.id } %>
<% end %>
<h2 style="display: inline;"><%= @food.name %></h2> <span style="display: inline;"><font size="1"><%= @food.show_food_type %></font></span>


<p>
  <%= @food.description %>
</p>
<p>
  <strong>Calories:</strong>
  <%= @food.calories %>
</p>
<p>
  <strong>Cost:</strong>
  <%= number_to_currency(@food.cost)%>
</p>

<div id="food-status">
<% if !@ef.nil? && can?(:modify, @ef) %>
<%= button_to "Oops! I didn't eat this", { :controller => 'foods', :action => 'unmark_as_eaten', :ef_id => @ef.id }, :class => :destroy %>
<% elsif logged_in? %>
<%= button_to "I ate this", { :controller => 'foods', :action => 'mark_as_eaten', :food_id => @food.id } %>
<% end %>
</div>