config/routes.rb
FreddieFit::Application.routes.draw do
  resources :foods

  get "home/index"

  resources :announcements

  resources :events

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  match 'event/register' => 'events#register', :as => :register_for_event  
  match 'event/unregister' => 'events#unregister', :as => :unregister_for_event

  match 'show_classes' => 'events#show_classes', :as => :show_classes

  match 'food/favorites/add' => 'foods#add_favorite', :as => :add_favorite_food
  match 'food/favorites/remove' => 'foods#remove_favorite', :as => :remove_favorite_food
  match 'food/mark_as_eaten' => 'foods#mark_as_eaten', :as => :mark_food_as_eaten
  match 'food/unmark_as_eaten' => 'foods#unmark_as_eaten', :as => :unmark_food_as_eaten

  resources :sessions

  resources :users

  root :to => 'home#index'

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : "Welcome to FreddieFit!" %></title>
  <%= stylesheet_link_tag "application", 'jquery-ui-1.10.1.custom', 'uniform.default', 'datagrid' %>
  <%= javascript_include_tag 'jquery', 'jquery-ui-1.10.1.custom', 'application', 'jquery_ujs' %>
  <%# javascript_include_tag :all %>

  <%= csrf_meta_tag %>
  <%= yield(:head) %>
</head>
<body>


  <div id="header" style="">
    <h1>
      Will YOU be <em><strong><font style="color: #0475CB;">Freddie</font><font style="color: #77B021;">Fit</font></strong></em>?
    </h1>
  </div>
  <div id="navigation" class="invertedshiftdown">
    <ul>
      <li><%= link_to "Home", root_url %></li>
      <li><%= link_to "Events", events_path %></li>
      <li><%= link_to "Announcements", announcements_path %></li>
      <li><%= link_to "Food", foods_path %></li>
      <li><%= link_to "Menus", "#" %></li>
      <li><%= link_to "Classes", show_classes_path %></li>


    </ul>


    <% if !logged_in? %>

    <div id="login_form">

      <p>
        <%= form_tag sessions_path do -%>
        <label for="login">Username</label>&nbsp;<%= text_field_tag 'login' %>&nbsp;<label for="password">Password</label>&nbsp;<%= password_field_tag 'password' %>&nbsp;&nbsp;<%= submit_tag 'Log in', :class => 'sigin_submit' %>
        <% end -%>
        <!--  <label for="remember_me">Remember me:</label><%# check_box_tag 'remember_me' %> -->
        <!-- Forgot Password? <%# link_to 'Click Here', "#", { :class => 'resetpassword' } %> -->
      </p>

    </div>

    <% else %>

    <div id="nav-account">

      <ul>
        <li>Welcome, <%= current_user.nice_name %></li>
        <li><%= link_to 'My Account', edit_current_user_path %></li>
        <li><%= link_to 'Logout', logout_path %></li>
      </ul>

    </div>

    <% end %>

    <br style="clear: both;" />
  </div>


  <div id="container">


    <%= show_flash_message(:fade => 10) %>

    <%= content_tag :h1, yield(:title) if show_title? %>
    <%= yield %>
  </div>
  <footer>
    Webmasters: Ryan Sanders & Karl Dockery II
  </footer>
</body>
</html>